sudo: false
language: cpp

matrix:
  include:
  - os: linux
    env: PYTHON=3.6
  - os: linux
    env: CONDA=3.6
  - os: osx
    env: PYTHON=3.6
  - os: osx
    env: CONDA=3.6

compiler:
  - gcc
  - clang

script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - ./test/run_tests
